%% -*- mode: erlang; -*-
%% vim: set ft=erlang:

{relx, Releases} = case lists:keyfind(relx, 1, CONFIG) of
                       'false' ->
                           {relx, []};
                       Relx -> Relx
                   end,

IsDev = lists:foldl(fun(_, true) -> true;
                       ({release, _Name, _Apps}, Acc) -> Acc;
                       ({release, _Name, _Apps, RelConfig}, _Acc) ->
                           proplists:get_value('mode', RelConfig) =:= 'dev'
                               orelse proplists:get_value('dev_mode', RelConfig) =:= true;
                       ({mod, dev}, _Acc) ->
                            true;
                       ({dev_mod, true}, _Acc) ->
                            false;
                       (_Other, Acc) ->
                            Acc
                    end
                   ,false
                   ,Releases
                   ),
ToFilterOut = [".erlang.mk"
              ,"ci.erlang.mk"
              ,".settings"
              ,".git"
              ,".circleci"
              ,"skel"
              ,"ananke"
              ,"amqp_leader"
              ],

ProjectApps = [{list_to_atom(App), 'load'}
               || TopDir <- ["applications", "core"],
                  Dir <- filelib:wildcard(filename:join([TopDir, "*"])),
                  App <- [filename:basename(Dir)],
                  filelib:is_dir(Dir),
                  filelib:is_dir(filename:join([Dir, "ebin"]))
                      orelse filelib:is_dir(filename:join([Dir, "src"])),
                  not lists:member(App, ToFilterOut)
              ],

BaseApps = [runtime_tools
           ,tools
           ,debugger
           ,sasl
           ],

RelxConfig = fun() ->
                     APPS = ProjectApps,
                     lists:foldr(fun({release, Name, Apps}, Acc) ->
                                         [{release, Name, Apps ++ APPS}|Acc];
                                    ({release, Name, Apps, RelConfig}, Acc) ->
                                         [{release, Name, Apps ++ APPS, RelConfig}|Acc];
                                    (Other, Acc) ->
                                         [Other|Acc]
                                 end
                                ,[]
                                ,Releases
                                )
             end,

AppsHash = case filelib:wildcard("make/.apps.mk.*") of
               [] -> undefined;
               [AppsHashFile] ->
                   "."++Hash = filename:extension(AppsHashFile),
                   Hash
           end,

case AppsHash of
    undefined ->
        io:format("You must run 'make fetch-core fetch-apps' first"),
        halt(1);
    _ ->
        ok
end,

%% this doesn't really work good, we need at least to hash of:
%% - make/.core.mk.*
%% - make/.more_apps.mk.*
%% - rebar3.config
%% otherwise we have to delete the rebar has file everytime.
%% RebarHashFile = "make/.rebar.config.script."++AppsHash,

%% add your config here, this dynamic config will be get cached
%% in rebar script hash file.
DynamicConfig =
fun() ->
        [{relx, RelxConfig()}
        ]
end,

PrepareRebarConfig = fun(MyConfig) ->
                             lists:foldl(fun({Key, Value}, Acc) ->
                                                 lists:keystore(Key, 1, Acc, {Key, Value})
                                         end
                                        ,CONFIG
                                        ,MyConfig
                                        )
                     end,

%% This doesn't work, see note above about hash file
%% To speed up, either use cache if exists or create and cache a new dynamic config
%% then merge to rebar CONFIG.
%% case file:read_file(RebarHashFile) of
%%     {ok, Bin} ->
%%         PrepareRebarConfig(erlang:binary_to_term(Bin));
%%     {error, _} ->
%%         NewConfig = DynamicConfig(),
%%         ok = file:write_file(RebarHashFile, erlang:term_to_binary(NewConfig)),
%%         PrepareRebarConfig(NewConfig)
%% end.


%% Hopefuly temporary, see note above hash file
NewConfig = PrepareRebarConfig(DynamicConfig()),

case filelib:is_file("rebar.local.config") of
    true ->
        Bindings = lists:foldr(fun({Key, Value}, Acc) -> erl_eval:add_binding(Key, Value, Acc) end
                              ,[{'CONFIG', NewConfig}
                               ,{'BASE_APPS', BaseApps}
                               ,{'PROJECT_APPS', ProjectApps}
                               ]
                              ,erl_eval:new_bindings()
                              ),
        {ok, ConfigTerms} = file:script("rebar.local.config", Bindings),
        ConfigTerms;
    Error ->
        NewConfig
end.
