CWD = $(shell pwd -P)
ROOT ?= $(realpath $(CWD)/..)
ERLANG_MK_FILENAME = $(ROOT)/erlang.mk

DEPS_MK ?= $(ROOT)/make/deps.mk

DEPS_DIR ?= $(ROOT)/deps

ERLC_OPTS += +debug_info -DWITH_JIFFY=1

.DEFAULT_GOAL := all

clean::
	$(if $(wildcard ./*/), rm -rf ./*/)
	$(if $(wildcard .erlang.mk), rm -rf .erlang.mk)

ifneq (,$(wildcard $(DEPS_MK)))
include $(DEPS_MK)
endif

include $(ROOT)/make/deps.mk
include $(ROOT)/erlang.mk
